#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3

# Remove trailing "/" for next commands
path=${path%/}

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong user"
    exit 1
fi
sudo yunohost app setting ajenti admin_user -v $user

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a ajenti
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


sudo sh -c "echo 'deb http://repo.ajenti.org/debian main main debian' > /etc/apt/sources.list.d/ajenti.list"

sudo wget http://repo.ajenti.org/debian/key -O- | apt-key add -

sudo apt-get update
sudo apt-get install -y ajenti

sudo service ajenti restart

# Add OpenVPN to YunoHost's monitored services
sudo yunohost service add ajenti --log /var/log/ajenti.log

sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/ajenti.conf


# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
